-- CopperEmber.luau
return {
	Accent = Color3.fromRGB(203, 120, 60),

	AcrylicMain = Color3.fromRGB(30, 22, 16),
	AcrylicBorder = Color3.fromRGB(100, 60, 40),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(255, 170, 110), Color3.fromRGB(150, 60, 25)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(130, 78, 48),
	Tab = Color3.fromRGB(210, 150, 120),

	Element = Color3.fromRGB(150, 100, 75),
	ElementBorder = Color3.fromRGB(40, 28, 20),
	InElementBorder = Color3.fromRGB(203, 120, 60),
	ElementTransparency = 0.88,

	ToggleSlider = Color3.fromRGB(185, 110, 70),
	ToggleToggled = Color3.fromRGB(12, 8, 6),

	SliderRail = Color3.fromRGB(185, 110, 70),

	DropdownFrame = Color3.fromRGB(200, 140, 105),
	DropdownHolder = Color3.fromRGB(70, 44, 32),
	DropdownBorder = Color3.fromRGB(48, 30, 20),
	DropdownOption = Color3.fromRGB(170, 115, 85),

	Keybind = Color3.fromRGB(140, 90, 60),

	Input = Color3.fromRGB(150, 100, 75),
	InputFocused = Color3.fromRGB(18, 12, 10),
	InputIndicator = Color3.fromRGB(230, 165, 115),

	Dialog = Color3.fromRGB(70, 45, 35),
	DialogHolder = Color3.fromRGB(56, 36, 28),
	DialogHolderLine = Color3.fromRGB(42, 26, 18),
	DialogButton = Color3.fromRGB(70, 45, 35),
	DialogButtonBorder = Color3.fromRGB(140, 85, 55),
	DialogBorder = Color3.fromRGB(95, 60, 40),
	DialogInput = Color3.fromRGB(120, 80, 60),
	DialogInputLine = Color3.fromRGB(230, 165, 115),

	Text = Color3.fromRGB(250, 245, 240),
	SubText = Color3.fromRGB(190, 165, 145),
	Hover = Color3.fromRGB(203, 120, 60),
	HoverChange = 0.05
}
