return {
	Accent = Color3.fromRGB(105, 180, 215),

	AcrylicMain = Color3.fromRGB(16, 22, 34),
	AcrylicBorder = Color3.fromRGB(36, 72, 96),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(28, 62, 106), Color3.fromRGB(100, 180, 215)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(42, 84, 116),
	Tab = Color3.fromRGB(150, 200, 225),

	Element = Color3.fromRGB(86, 122, 148),
	ElementBorder = Color3.fromRGB(16, 30, 44),
	InElementBorder = Color3.fromRGB(105, 180, 215),
	ElementTransparency = 0.82,

	ToggleSlider = Color3.fromRGB(112, 170, 200),
	ToggleToggled = Color3.fromRGB(8, 10, 16),

	SliderRail = Color3.fromRGB(112, 170, 200),

	DropdownFrame = Color3.fromRGB(160, 200, 220),
	DropdownHolder = Color3.fromRGB(20, 40, 60),
	DropdownBorder = Color3.fromRGB(16, 32, 48),
	DropdownOption = Color3.fromRGB(132, 180, 205),

	Keybind = Color3.fromRGB(112, 170, 200),

	Input = Color3.fromRGB(122, 185, 210),
	InputFocused = Color3.fromRGB(10, 12, 18),
	InputIndicator = Color3.fromRGB(186, 220, 235),

	Dialog = Color3.fromRGB(20, 36, 54),
	DialogHolder = Color3.fromRGB(16, 32, 50),
	DialogHolderLine = Color3.fromRGB(12, 24, 38),
	DialogButton = Color3.fromRGB(20, 36, 54),
	DialogButtonBorder = Color3.fromRGB(72, 124, 150),
	DialogBorder = Color3.fromRGB(34, 64, 92),
	DialogInput = Color3.fromRGB(46, 92, 118),
	DialogInputLine = Color3.fromRGB(186, 220, 235),

	Text = Color3.fromRGB(242, 246, 250),
	SubText = Color3.fromRGB(170, 190, 200),
	Hover = Color3.fromRGB(112, 170, 200),
	HoverChange = 0.04
}
