-- FrozenAurora.luau
return {
	Accent = Color3.fromRGB(115, 200, 255),

	AcrylicMain = Color3.fromRGB(16, 24, 36),
	AcrylicBorder = Color3.fromRGB(40, 80, 110),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(30, 70, 120), Color3.fromRGB(120, 200, 255)),
	AcrylicNoise = 0.95,

	TitleBarLine = Color3.fromRGB(45, 90, 125),
	Tab = Color3.fromRGB(170, 210, 240),

	Element = Color3.fromRGB(90, 130, 160),
	ElementBorder = Color3.fromRGB(18, 32, 46),
	InElementBorder = Color3.fromRGB(115, 200, 255),
	ElementTransparency = 0.83,

	ToggleSlider = Color3.fromRGB(120, 190, 230),
	ToggleToggled = Color3.fromRGB(8, 12, 18),

	SliderRail = Color3.fromRGB(120, 190, 230),

	DropdownFrame = Color3.fromRGB(170, 210, 235),
	DropdownHolder = Color3.fromRGB(22, 44, 66),
	DropdownBorder = Color3.fromRGB(18, 36, 54),
	DropdownOption = Color3.fromRGB(140, 190, 220),

	Keybind = Color3.fromRGB(120, 190, 220),

	Input = Color3.fromRGB(130, 200, 230),
	InputFocused = Color3.fromRGB(12, 16, 24),
	InputIndicator = Color3.fromRGB(200, 235, 255),

	Dialog = Color3.fromRGB(22, 40, 60),
	DialogHolder = Color3.fromRGB(18, 34, 52),
	DialogHolderLine = Color3.fromRGB(14, 28, 42),
	DialogButton = Color3.fromRGB(22, 40, 60),
	DialogButtonBorder = Color3.fromRGB(80, 140, 170),
	DialogBorder = Color3.fromRGB(36, 72, 100),
	DialogInput = Color3.fromRGB(50, 100, 130),
	DialogInputLine = Color3.fromRGB(200, 235, 255),

	Text = Color3.fromRGB(245, 250, 255),
	SubText = Color3.fromRGB(175, 195, 205),
	Hover = Color3.fromRGB(120, 190, 230),
	HoverChange = 0.04
}
