-- NeonTide.luau
return {
	Accent = Color3.fromRGB(48, 200, 255),

	AcrylicMain = Color3.fromRGB(8, 12, 24),
	AcrylicBorder = Color3.fromRGB(28, 60, 80),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(10, 20, 40), Color3.fromRGB(24, 120, 140)),
	AcrylicNoise = 0.93,

	TitleBarLine = Color3.fromRGB(22, 60, 80),
	Tab = Color3.fromRGB(140, 220, 230),

	Element = Color3.fromRGB(40, 70, 90),
	ElementBorder = Color3.fromRGB(6, 10, 18),
	InElementBorder = Color3.fromRGB(48, 200, 255),
	ElementTransparency = 0.85,

	ToggleSlider = Color3.fromRGB(90, 200, 220),
	ToggleToggled = Color3.fromRGB(6, 10, 18),

	SliderRail = Color3.fromRGB(90, 200, 220),

	DropdownFrame = Color3.fromRGB(120, 180, 190),
	DropdownHolder = Color3.fromRGB(14, 28, 46),
	DropdownBorder = Color3.fromRGB(10, 20, 30),
	DropdownOption = Color3.fromRGB(140, 210, 220),

	Keybind = Color3.fromRGB(120, 200, 210),

	Input = Color3.fromRGB(110, 190, 200),
	InputFocused = Color3.fromRGB(6, 8, 14),
	InputIndicator = Color3.fromRGB(180, 230, 240),

	Dialog = Color3.fromRGB(18, 34, 50),
	DialogHolder = Color3.fromRGB(12, 24, 36),
	DialogHolderLine = Color3.fromRGB(8, 16, 26),
	DialogButton = Color3.fromRGB(18, 34, 50),
	DialogButtonBorder = Color3.fromRGB(60, 100, 110),
	DialogBorder = Color3.fromRGB(28, 56, 72),
	DialogInput = Color3.fromRGB(30, 60, 75),
	DialogInputLine = Color3.fromRGB(180, 230, 240),

	Text = Color3.fromRGB(240, 248, 255),
	SubText = Color3.fromRGB(170, 190, 200),
	Hover = Color3.fromRGB(90, 200, 220),
	HoverChange = 0.06
}
