-- Solarflare.luau
return {
	Accent = Color3.fromRGB(255, 140, 40),

	AcrylicMain = Color3.fromRGB(28, 18, 12),
	AcrylicBorder = Color3.fromRGB(80, 45, 30),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(255, 160, 80), Color3.fromRGB(120, 30, 10)),
	AcrylicNoise = 0.92,

	TitleBarLine = Color3.fromRGB(140, 70, 40),
	Tab = Color3.fromRGB(200, 140, 110),

	Element = Color3.fromRGB(160, 100, 70),
	ElementBorder = Color3.fromRGB(30, 20, 15),
	InElementBorder = Color3.fromRGB(255, 140, 40),
	ElementTransparency = 0.90,

	ToggleSlider = Color3.fromRGB(200, 120, 70),
	ToggleToggled = Color3.fromRGB(10, 8, 6),

	SliderRail = Color3.fromRGB(200, 120, 70),

	DropdownFrame = Color3.fromRGB(220, 150, 110),
	DropdownHolder = Color3.fromRGB(70, 40, 30),
	DropdownBorder = Color3.fromRGB(45, 25, 18),
	DropdownOption = Color3.fromRGB(190, 120, 80),

	Keybind = Color3.fromRGB(150, 90, 60),

	Input = Color3.fromRGB(160, 100, 70),
	InputFocused = Color3.fromRGB(18, 10, 8),
	InputIndicator = Color3.fromRGB(240, 170, 120),

	Dialog = Color3.fromRGB(70, 40, 30),
	DialogHolder = Color3.fromRGB(55, 35, 25),
	DialogHolderLine = Color3.fromRGB(38, 22, 16),
	DialogButton = Color3.fromRGB(70, 40, 30),
	DialogButtonBorder = Color3.fromRGB(135, 75, 45),
	DialogBorder = Color3.fromRGB(100, 60, 40),
	DialogInput = Color3.fromRGB(120, 80, 55),
	DialogInputLine = Color3.fromRGB(240, 170, 120),

	Text = Color3.fromRGB(250, 245, 240),
	SubText = Color3.fromRGB(200, 175, 155),
	Hover = Color3.fromRGB(255, 140, 40),
	HoverChange = 0.05
}
