return {
	Accent = Color3.fromRGB(88, 180, 120),

	AcrylicMain = Color3.fromRGB(14, 22, 18),
	AcrylicBorder = Color3.fromRGB(30, 76, 56),
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(36, 82, 64), Color3.fromRGB(12, 46, 28)),
	AcrylicNoise = 0.90,

	TitleBarLine = Color3.fromRGB(28, 82, 56),
	Tab = Color3.fromRGB(150, 200, 170),

	Element = Color3.fromRGB(106, 150, 125),
	ElementBorder = Color3.fromRGB(18, 36, 28),
	InElementBorder = Color3.fromRGB(88, 180, 120),
	ElementTransparency = 0.80,

	ToggleSlider = Color3.fromRGB(96, 170, 110),
	ToggleToggled = Color3.fromRGB(8, 12, 10),

	SliderRail = Color3.fromRGB(96, 170, 110),

	DropdownFrame = Color3.fromRGB(150, 200, 170),
	DropdownHolder = Color3.fromRGB(18, 36, 28),
	DropdownBorder = Color3.fromRGB(14, 28, 22),
	DropdownOption = Color3.fromRGB(120, 185, 145),

	Keybind = Color3.fromRGB(110, 172, 135),

	Input = Color3.fromRGB(112, 178, 140),
	InputFocused = Color3.fromRGB(10, 16, 12),
	InputIndicator = Color3.fromRGB(160, 220, 180),

	Dialog = Color3.fromRGB(20, 40, 30),
	DialogHolder = Color3.fromRGB(14, 30, 22),
	DialogHolderLine = Color3.fromRGB(10, 20, 16),
	DialogButton = Color3.fromRGB(20, 40, 30),
	DialogButtonBorder = Color3.fromRGB(56, 112, 84),
	DialogBorder = Color3.fromRGB(30, 64, 46),
	DialogInput = Color3.fromRGB(40, 78, 56),
	DialogInputLine = Color3.fromRGB(160, 220, 180),

	Text = Color3.fromRGB(238, 246, 238),
	SubText = Color3.fromRGB(160, 188, 165),
	Hover = Color3.fromRGB(96, 170, 110),
	HoverChange = 0.045
}
